export const UserCode = {
    PHONE_EXISTED: "101",
    EMAIL_EXISTED: "102",
    USER_NAME_EXISTED: "103",
    IDENTITY_INVALID: "104",
    NOT_ACTIVE: "105",
    NOT_LINK_BANK: "106",
    USER_ID_NOT_FOUND: "107",
    PASSWORD_INVALID: "108",
    USER_NAME_INVALID: "109",
    EMAIL_INVALID: "110",
    PIN_FAIL: "110", // LOGIN
    PIN_FAIL_WARN: "111", // LOGIN WARN
    PIN_FAIL_LOCK: "112", // LOGIN LOCK
    OTP_FAIL: "113",
    OTP_FAIL_WARN: "114",
    OTP_FAIL_LOCK: "115",
    USER_BLOCK: "116",
    NOT_ENOUGH_BALANCE: "119",
    DEVICE_INVALID: "120",
    DEVICE_EXISTED: "121",
    CODE_EXISTED: "122",
    EMAIL_NOT_EXISTS: "123",
    NOT_ENOUGH_POKE: "124",
    NOT_ENOUGH_TICKET: "125",
  };